spring:
  application:
    name: ecom-order-service

server:
  port: 8080

logging:
  level:
    org.codesnippet.ecomorderservice.client: DEBUG

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true